FROM ubuntu:22.04

RUN apt-get update
RUN apt-get -y install curl gnupg build-essential
RUN curl -sL https://deb.nodesource.com/setup_20.x  | bash -
RUN apt-get -y install nodejs

RUN apt-get -y install nano vim
